### 이메일 인증코드 전송
POST http://localhost:8080/auth/email/send
Content-Type: application/json

{
  "email": "rlawldbs9128@gmail.com"
}

### 이메일 인증코드 전송 유저1
POST http://localhost:8080/auth/email/send
Content-Type: application/json

{
  "email": "testuser1@example.com"
}

### 이메일 인증코드 전송 유저2
POST http://localhost:8080/auth/email/send
Content-Type: application/json

{
  "email": "testuser2@example.com"
}

### 이메일 인증코드 전송 로컬크리에이터1
POST http://localhost:8080/auth/email/send
Content-Type: application/json

{
  "email": "creator1@example.com"
}

### 이메일 인증코드 확인
POST http://localhost:8080/auth/email/verify
Content-Type: application/json

{
  "email": "rlawldbs9128@gmail.com",
  "code": "297352"
}

### 이메일 인증코드 확인 유저1
POST http://localhost:8080/auth/email/verify
Content-Type: application/json

{
  "email": "testuser1@example.com",
  "code": "164401"
}

### 이메일 인증코드 확인 유저2
POST http://localhost:8080/auth/email/verify
Content-Type: application/json

{
  "email": "testuser2@example.com",
  "code": "455278"
}

### 이메일 인증코드 확인 로컬크리에이터1
POST http://localhost:8080/auth/email/verify
Content-Type: application/json

{
  "email": "creator1@example.com",
  "code": "134845"
}