### 관리자 로그인 - env에 저장된걸로 바꿔서 로그인해주세요
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "Admin001@salayo.com",
  "password": "Adminpass1@"
}

> {%
  const json = response.body;
  const accessToken = json.data.accessToken;
  client.global.set("accessToken", accessToken);
%}

### 매거진 썸네일 이미지 업로드(단일 업로드)
POST http://localhost:8080/magazine/files/upload?purpose=THUMBNAIL
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data

--boundary
Content-Disposition: form-data; name="files"; filename="thumbnail.jpg"
Content-Type: image/jpeg

< ./thumbnail.jpg
--boundary--

### 매거진 상세 이미지 파일 업로드 테스트(다중 업로드)
POST http://localhost:8080/magazine/files/upload?purpose=DETAIL_IMAGE
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data

--boundary
Content-Disposition: form-data; name="files"; filename="img1.jpg"
Content-Type: image/jpeg

< ./img1.jpg
--boundary
Content-Disposition: form-data; name="files"; filename="img2.jpg"
Content-Type: image/jpeg

< ./img2.jpg
--boundary--

### 매거진 임시등록 (관리자)
POST http://localhost:8080/admin/magazines
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "테스트으!!",
  "content": "<h2>피드백 잘 들어오나요?</h2><p>음음음음ㅇ...</p><img src=\"https://s3.amazonaws.com/local-life-s3/magazine/jeju.jpg\"/>",
  "regionCategoryId": 2,
  "aptitudeCategoryId": 2,
  "thumbnailUrl": "https://s3.amazonaws.com/local-life-s3/magazine/jeju-thumb.jpg",
  "localCreatorId": 1
}

### 임시등록 매거진 목록 조회(DRAFT 리스트)
GET http://localhost:8080/admin/magazines?page=0&size=5
Authorization: Bearer {{accessToken}}

### 임시등록 매거진 상세조회(DRAFT)
GET http://localhost:8080/admin/magazines/13
Authorization: Bearer {{accessToken}}

### 매거진 초안 확인 링크 전송
POST http://localhost:8080/admin/magazines/16/preview/send
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### 매거진 수정본 확인 링크 전송
POST http://localhost:8080/admin/magazines/16/revision/send
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### 피드백 기반 매거진 수정 (관리자 전용)
PUT http://localhost:8080/admin/magazines/16/feedback
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content": "수정된 매거진 본문 내용입니다. 새로운 인터뷰 내용을 반영했습니다."
}

### 로컬 크리에이터 로그인 (승인 여부 확인 포함)
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "creator1@example.com",
  "password": "Password123!"
}

> {%
  const json = response.body;
  const accessToken = json.data.accessToken;
  client.global.set("accessToken", accessToken);
%}

### 매거진 피드백 등록 성공
POST http://localhost:8080/localcreator/magazines/16/feedbacks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content": "첫 번째 수정 요청입니다. 본문 일부 문장을 조금 더 간결하게 다듬어주세요."
}

### 매거진 피드백 등록 실패 (최대 3회 초과)
POST http://localhost:8080/localcreator/magazines/1/feedbacks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content": "네 번째 피드백 시도입니다."
}

### 매거진 피드백 목록 조회 (로컬 크리에이터)
GET http://localhost:8080/localcreator/magazines/15/feedbacks
Authorization: Bearer {{accessToken}}

### 매거진 수정 이력 조회
GET http://localhost:8080/admin/magazines/13/revisions
Authorization: Bearer {{accessToken}}
Accept: application/json

### 매거진 미리보기 토큰 검증
POST http://localhost:8080/localcreator/magazines/preview/validate?token=3260c1e8-2051-45e8-8b12-e2d0bbfdb24e
Authorization: Bearer {{accessToken}}
Content-Type: application/json

### 로컬 크리에이터 로그인 (승인 여부 확인 포함)
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "creator1@example.com",
  "password": "Password123!"
}

> {%
  const json = response.body;
  const accessToken = json.data.accessToken;
  client.global.set("accessToken", accessToken);
%}

### 매거진 피드백 등록 성공
POST http://localhost:8080/localcreator/magazines/8/feedbacks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content": "첫 번째 수정 요청입니다. 본문 일부 문장을 조금 더 간결하게 다듬어주세요."
}

### 매거진 피드백 등록 실패 (최대 3회 초과)
POST http://localhost:8080/localcreator/magazines/1/feedbacks
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content": "네 번째 피드백 시도입니다."
}

### 매거진 피드백 목록 조회 (로컬 크리에이터)
GET http://localhost:8080/localcreator/magazines/8/feedbacks
Authorization: Bearer {{accessToken}}
