
### 멤버(일반 회원) 로그인
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "testuser2@example.com",
  "password": "Test1234!"
}

> {%
  const json = response.body;
  const accessToken = json.data.accessToken;
  client.global.set("accessToken", accessToken);
%}

### 체험 프로그램 스케줄 예약
POST http://localhost:8080/reservation
Content-Type: application/json

{

}
