
### 멤버(일반 회원) 로그인
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "testuser1@example.com",
  "password": "test1234!"
}

> {%
  const json = response.body;
  const accessToken = json.data.accessToken;
  client.global.set("accessToken", accessToken);
%}

### 체험 프로그램 스케줄 예약 (임시 테스트용)
POST http://localhost:8080/reservation
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "reservationCreateRequestDto": {
    "programScheduleId": 1
  },
  "paymentCreateRequestDto": {
    "pgTid": "pg_test_1234567890",
    "impUid": "imp_test_1234567890",
    "paymentCost": 1000,
    "paymentCard": "신한카드",
    "paymentMethodType": "CARD"
  }
}
