### 리뷰 작성
POST http://localhost:8080/programs/1/reviews?reservationId=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "정말 좋은 체험이었습니다!"
}

### 리뷰 답글 작성
POST http://localhost:8080/reviews/1/replies
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "소중한 후기 감사합니다!"
}

### 내 리뷰 조회
# page: 0부터 시작, size: 페이지당 개수, sort: 정렬할 필드,정렬방향(asc/desc)
GET http://localhost:8080/my/reviews?page=0&size=5&sort=createdAt,desc
Authorization: Bearer {{authToken}}

### 프로그램 리뷰 조회
GET http://localhost:8080/programs/1/reviews?page=0&size=10&sort=reviewRating,desc

### 관리자 전체 리뷰 조회
GET http://localhost:8080/admin/reviews?page=1&size=20
Authorization: Bearer {{authToken}}

### 리뷰 수정
PUT http://localhost:8080/reviews/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "정말 좋은 체험이었습니다! 다시 참여하고 싶어요."
}

### 리뷰 삭제
DELETE http://localhost:8080/reviews/1
Authorization: Bearer {{authToken}}
